/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Crontab: typeof import('./src/components/Crontab/index.vue')['default']
    Day: typeof import('./src/components/Crontab/day.vue')['default']
    DictTag: typeof import('./src/components/DictTag/index.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload/index.vue')['default']
    HandleProcess: typeof import('./src/components/HandleProcess/index.vue')['default']
    Hour: typeof import('./src/components/Crontab/hour.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector/index.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload/index.vue')['default']
    List: typeof import('./src/components/IconSelector/list.vue')['default']
    Min: typeof import('./src/components/Crontab/min.vue')['default']
    Month: typeof import('./src/components/Crontab/month.vue')['default']
    NoticeBar: typeof import('./src/components/NoticeBar/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    Result: typeof import('./src/components/Crontab/result.vue')['default']
    RightToolbar: typeof import('./src/components/RightToolbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Second: typeof import('./src/components/Crontab/second.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TAvatar: typeof import('./src/components/TAvatar/index.vue')['default']
    Tinymce: typeof import('./src/components/tinymce/index.vue')['default']
    TSearchSelect: typeof import('./src/components/TSearchSelect/index.vue')['default']
    VanCascader: typeof import('vant/es')['Cascader']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSlider: typeof import('vant/es')['Slider']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    Verification: typeof import('./src/components/Verifition/verification.vue')['default']
    Verify: typeof import('./src/components/Verifition/Verify.vue')['default']
    VerifyPoints: typeof import('./src/components/Verifition/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./src/components/Verifition/Verify/VerifySlide.vue')['default']
    Vue3Marquee: typeof import('./src/components/Vue3Marquee/index.vue')['default']
    Week: typeof import('./src/components/Crontab/week.vue')['default']
    Year: typeof import('./src/components/Crontab/year.vue')['default']
  }
}
